version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: book-review-frontend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: book-review-backend
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/bookreview
  mongo:
    image: mongo:7
    restart: unless-stopped
    container_name: book-review-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
